[package]
name = "accounts-ui"
version = "0.1.0"
edition = "2024"

[dependencies]

[target.'cfg(target_arch = "wasm32")'.dependencies]
dioxus = { version = "0.7.3", features = ["web"] }
dioxus-web = "0.7.3"
gloo-net = "0.6"
protocol = { workspace = true }
protocol_accounts = { workspace = true }
common_json = { workspace = true }
serde = { workspace = true }
getrandom = { version = "0.3", features = ["wasm_js"] }
