[package]
name = "hospital_tycoon_ui"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "hospital_tycoon_ui"
path = "src/main.rs"

[dependencies]
serde = { workspace = true }
serde_json = "1.0"
thiserror = { workspace = true }
anyhow = { workspace = true }
