[workspace]
members = [
  "backend",
  "projects/libraries/ai",
  "projects/libraries/common",
  "projects/libraries/neural",
  "projects/libraries/protocol",
  "projects/libraries/security",
  "projects/libraries/symbolic",
  "projects/libraries/ui",
  "projects/products/core/central_ui",
  "projects/products/core/engine",
  "projects/products/core/launcher",
  "projects/products/core/watcher",
  "projects/products/varina/backend",
  "projects/products/varina/ui",
  "ui",
]
resolver = "2"
