[package]
name = "protocol-builder-tooling"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "protocol_builder_tooling"
path = "src/main.rs"

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
common_json = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }
