[package]
name = "vod-forge-backend"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "vod_forge_backend"
path = "src/main.rs"

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }
common_json = { workspace = true }

[dev-dependencies]
tempfile = "3"
