[package]
name = "platform-versioning-backend"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "platform-versioning-backend"
path = "src/main.rs"

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tokio = { workspace = true }
bincode = { workspace = true }
anyhow = { workspace = true }
serde_json = "1.0"
sha2 = { workspace = true }
hex = { workspace = true }
axum = { workspace = true }
tower = { workspace = true }
http = { workspace = true }

[dev-dependencies]
