[package]
name = "simkernel_tooling"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "simkernel_tooling"
path = "src/main.rs"

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
serde_json = "1.0"

[dev-dependencies]
