[package]
name = "protocol"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
common_time = { workspace = true }
common_json = { workspace = true }
protocol_macros = { workspace = true }
common = { workspace = true }
