[package]
name = "evolutionary_system_generator_ui"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "evo-ui"
path = "src/main.rs"

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
serde_json = "1"
evolutionary_system_generator_backend = { path = "../backend" }
