[package]
name = "auto_manager_ai"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "auto_manager_ai"
path = "src/bin/auto_manager_ai.rs"

[dependencies]
serde = { workspace = true }
common_json = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
