[package]
name = "vod-forge-ui"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "vod_forge_ui"
path = "src/main.rs"

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
common_json = { workspace = true }
