[package]
name = "launcher"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
ctrlc = "3"
serde = { workspace = true }
clap = { version = "4", features = ["derive"] }
toml = { workspace = true }
ureq = "3"
