[package]
name = "git_lib"
version = "0.1.0"
edition = "2024"

authors = ["Your Name <your.email@example.com>"]
description = "[ABANDONED] A modular library for interacting with Git repositories."
license = "MIT"

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
