[package]
name = "pjson_proc_macros"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
ast_core = { workspace = true }
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full"] }
