[package]
name = "versioning"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
chrono = { version = "0.4", features = ["serde"] }
serde_json = "1.0"
