[package]
name = "symbolic"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
regex = "1.7"
syn = { version = "2.0", features = ["full"] }
common = { workspace = true }
