[package]
name = "symbolic"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = { workspace = true }
serde = { workspace = true }
regex = "1.7"
syn = { version = "2.0", features = ["full"] }
common = { workspace = true }
tracing = { workspace = true }
