[package]
name = "autonomy_orchestrator_ai"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
serde = { workspace = true }
common_json = { workspace = true }
common_ron = { workspace = true }
common_binary = { workspace = true }
